feat: create login view and logic
Voirsy/voirsy-front-end pull request #13
Opened 2021-10-27 21:59 UTC by pawelsobkowski

Closes Voirsy/voirsy-front-end#5

Before merging this PR, related [PR](https://github.com/Voirsy/back-end/pull/3) with login logic improvements should be merged first. Also, for testing purposes, it required to use backend with changes from this [branch](https://github.com/Voirsy/back-end/tree/fix/login-logic)

2021-10-28 18:16 UTC, zawolanski requested changes
I didn't mark input labels but it should have translations too.

2021-10-28 18:16 UTC, zawolanski commented on src/components/Header/index.tsx
> +  }, [fullname]);
Why are you using state here? Couldn't we just use `fullname` fetched from the Redux on line 28?

2021-10-28 18:16 UTC, zawolanski commented on src/components/Header/index.tsx
> +  const isAuth = (): boolean => (!!localStorage.getItem('JWT_TOKEN') ? true : false);
I think this method could be moved to a separate file like `helpers.ts` cause we will be using it in many places.

2021-10-28 18:16 UTC, zawolanski commented on src/views/Login/Components/LoginForm/index.tsx
> +            message: 'Field is required',
All validation messages should be moved to the translation file. I'll leave a 'Translation.' comment everywhere I'll notice such a situation.

2021-10-28 18:16 UTC, zawolanski commented on src/views/Login/Components/LoginForm/index.tsx
> +            message: 'Email should contains at least 3 characters',
Translation.

2021-10-28 18:16 UTC, zawolanski commented on src/views/Login/Components/LoginForm/index.tsx
> +            message: 'Invalid email address',
Translation.

2021-10-28 18:16 UTC, zawolanski commented on src/views/Login/Components/SignInForm/index.tsx
> +            message: 'Field is required',
Translation.

2021-10-28 18:16 UTC, zawolanski commented on src/views/Login/Components/SignInForm/index.tsx
> +            message: 'Email should contains at least 3 characters',
Translation.

2021-10-28 18:16 UTC, zawolanski commented on src/views/Login/Components/SignInForm/index.tsx
> +            message: 'Invalid email address',
Translation.

2021-10-28 18:16 UTC, zawolanski commented on src/views/Login/Components/SignInForm/index.tsx
> +            message: 'Password should contains at least 8 characters',
Translation.

2021-10-28 18:16 UTC, zawolanski commented on src/views/Login/Components/SignInForm/index.tsx
> +            message: 'Field is required',
Translation.

2021-10-28 18:16 UTC, zawolanski commented on src/views/Login/Components/SignInForm/index.tsx
> +    } catch (error: any) {
Could we please disable the `@typescript-eslint/no-explicit-any` Eslint on this line rule to avoid this ugly warning in the console?

2021-10-28 18:16 UTC, zawolanski commented on src/views/Login/Components/SignInForm/index.tsx
> +        Sign in
Translation.

2021-10-28 18:16 UTC, zawolanski commented on src/views/Login/Components/SignUpForm/index.tsx
> +            message: 'Field is required',
Translation.

2021-10-28 18:16 UTC, zawolanski commented on src/views/Login/Components/SignUpForm/index.tsx
> +            message: 'Field should contains at least 3 characters',
Translation.

2021-10-28 18:16 UTC, zawolanski commented on src/views/Login/Components/SignUpForm/index.tsx
> +            message: 'Field is required',
Translation.

2021-10-28 18:16 UTC, zawolanski commented on src/views/Login/Components/SignUpForm/index.tsx
> +            message: 'Invalid email address',
Translation.

2021-10-28 18:16 UTC, zawolanski commented on src/views/Login/Components/SignUpForm/index.tsx
> +            message: 'Email should contains at least 3 characters',
Translation.

2021-10-28 18:16 UTC, zawolanski commented on src/views/Login/Components/SignUpForm/index.tsx
> +        Create account
Translation.

2021-10-28 18:16 UTC, zawolanski commented on src/views/Login/Components/SignUpForm/index.tsx
> +            message: 'Password should contains at least 8 characters',
Translation.

2021-10-28 18:16 UTC, zawolanski commented on src/views/Login/Components/SignUpForm/index.tsx
> +            message: 'Field is required',
Translation.

2021-10-28 18:16 UTC, zawolanski commented on src/views/Login/Components/SignUpForm/index.tsx
> +    } catch (error: any) {
Same as before.

2021-10-28 18:16 UTC, zawolanski commented on src/views/Login/Components/SignUpForm/index.tsx
> +        <FormLabel component="legend">Account type</FormLabel>
Translation.

2021-10-28 18:16 UTC, zawolanski commented on src/views/Login/Components/SignUpForm/index.tsx
> +            label="Standard"
Translation.

2021-10-29 13:16 UTC, pawelsobkowski commented on src/views/Login/Components/LoginForm/index.tsx
> +            message: 'Field is required',
Ah, translation. I forgot about that.

2021-10-29 13:22 UTC, pawelsobkowski commented on src/components/Header/index.tsx
> +  }, [fullname]);
Right, `fullname` is sufficient.

2021-10-29 16:48 UTC, zawolanski approved these changes

2021-10-29 16:49 UTC, merged