refactor: create salon details in admin view
Voirsy/voirsy-front-end pull request #27
Opened 2021-12-06 19:35 UTC by pawelsobkowski

# Status

 - [x] Work in progress 👷‍♂️

# Type

- [x] Feat
- [x] Refactor

# Related issue

Voirsy/voirsy-front-end#23

# Description
Refactoring actual admin view, add Details, Calendar and Portfolio view

2021-12-27 16:09 UTC, pawelsobkowski commented
Generally, most of the view is done. IDK, if it makes any sense to wait for backend for the rest of the required features. We can merge this and create a task to finish admin view with desired features when will be available. What do you think @zawolanski ?

2021-12-27 16:19 UTC, zawolanski commented
> Generally, most of the view is done. IDK, if it makes any sense to wait for backend for the rest of the required features. We can merge this and create a task to finish admin view with desired features when will be available. What do you think @zawolanski ?

I fully agree with you. There is no sense to wait till the backend will be finished.

2021-12-27 18:19 UTC, zawolanski requested changes

2021-12-27 18:19 UTC, zawolanski commented on src/components/AdminPanelNavigation/adminPanelNavigation.list.tsx
> +        Add salon
Translation.

2021-12-27 18:19 UTC, zawolanski commented on src/templates/Salons/index.tsx
> +              </CustomEditHeader> */}
Is this comment could be deleted?

2021-12-28 10:45 UTC, zawolanski approved these changes

2021-12-29 13:38 UTC, merged